void employee_setearValorDeId(int idMaxEncontrado);
int controller_loadFromText(char* path ,LinkedList* pArrayListEmployee,int* pIdMaximo);
int controller_loadFromBinary(char* path , LinkedList* pArrayListEmployee,int* pIdMaximo);
int controller_addEmployee(LinkedList* pArrayListEmployee,int idMaximo);
int controller_ListEmployee(LinkedList* pArrayListEmployee);
int controller_editEmployee(LinkedList* pArrayListEmployee);
int controller_removeEmployee(LinkedList* pArrayListEmployee);
int controller_sortEmployee(LinkedList* pArrayListEmployee);
int controller_saveAsText(char* path , LinkedList* pArrayListEmployee);
int controller_saveAsBinary(char* path , LinkedList* pArrayListEmployee);
void imprimirempleadosDesdeLinkedlist(LinkedList* listaDinamica);
